hotkeys:
  shell: {}
ssh: {}
terminal:
  colorScheme:
    name: Dracula
    foreground: '#f8f8f2'
    background: '#1e1f29'
    cursor: '#bbbbbb'
    colors:
      - '#000000'
      - '#ff5555'
      - '#50fa7b'
      - '#f1fa8c'
      - '#bd93f9'
      - '#ff79c6'
      - '#8be9fd'
      - '#bbbbbb'
      - '#555555'
      - '#ff5555'
      - '#50fa7b'
      - '#f1fa8c'
      - '#bd93f9'
      - '#ff79c6'
      - '#8be9fd'
      - '#ffffff'
  frontend: xterm
  font: Source Code Pro for Powerline
  ligatures: true
  environment: {}
  shell: git-bash
  workingDirectory: 'D:\workspace'
  rightClick: paste
  copyOnSelect: true
  profiles: []
appearance:
  theme: Compact
  tabsLocation: bottom
  vibrancy: true
pluginBlacklist: []
